nginx-proxy:
   image: jwilder/nginx-proxy
   ports:
      - 80:80
      - 443:443
   labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: ""
   volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs:ro
      - /usr/share/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
