version: '2'

services:
   wordpress:
      image: wordpress:latest 
      links:
         - wordpress_db:mysql
      volumes:
         - ./code:/code
         - ./html:/var/www/html
      labels:
         - "traefik.backend=wordpress"
         - "traefik.frontend.rule=Host:wp.vm.test"
      networks:
         - web
   wordpress_db:
      image: mariadb
      environment: 
         MYSQL_ROOT_PASSWORD: ChangeMe123
         MYSQL_DATABASE: wordpress
      volumes:
         - ./database:/var/lib/mysql
      networks:
         - web

networks:
   web:
      external:
         name: traefik_webgateway

